// ─────────────────────────────────────────────────────────────────────────────
// regime.filter.js — NIFTY trend + high-volatility-day gate for the recommended
// system. Reads data/regime/nifty-regime.json (generated by the backtest's
// export-to-dashboard.js). If the file is absent, the gate is a no-op (allow all).
//
// LIVE NOTE: the snapshot suits REPLAY validation. For live trading, regenerate
// nifty-regime.json daily from fresh NIFTY data (trend EMA + 5d range%).
// ─────────────────────────────────────────────────────────────────────────────
'use strict';
const fs = require('node:fs');
const path = require('node:path');

const IST_OFFSET_MS = 5.5 * 60 * 60 * 1000;
const REGIME_FILE = path.resolve(__dirname, '..', '..', 'data', 'regime', 'nifty-regime.json');

let _regime = null, _loaded = false;
function load(){
  if (_loaded) return _regime;
  _loaded = true;
  try { _regime = JSON.parse(fs.readFileSync(REGIME_FILE, 'utf8')); _regime._blocked = new Set(_regime.blockedDays || []); }
  catch { _regime = null; }
  return _regime;
}
const tsMs = ts => ts > 1e12 ? ts : ts * 1000;
const istDay = ts => Math.floor((tsMs(ts) + IST_OFFSET_MS) / 86400000);
const bucket15 = ts => { const ms = tsMs(ts); const bk = 15*60*1000; return Math.floor(ms/bk)*bk/1000; };

function trendAt(ts){ const r = load(); if (!r || !r.trendByTs) return 0; const v = r.trendByTs[String(bucket15(ts))]; return v === undefined ? 0 : v; }
function isBlockedDay(ts){ const r = load(); return r && r._blocked ? r._blocked.has(istDay(ts)) : false; }

// allow(signal, ts): apply NIFTY trend + high-vol-day gate. Unknown regime => allow.
function allow(signal, ts){
  if (!load()) return true;            // no regime file -> no gating
  if (isBlockedDay(ts)) return false;  // skip high-vol whipsaw days
  const tr = trendAt(ts);
  if (tr === 0) return true;
  if (signal === 'LONG'  && tr < 0) return false;
  if (signal === 'SHORT' && tr > 0) return false;
  return true;
}

module.exports = { allow, trendAt, isBlockedDay, REGIME_FILE };
